spring:
  application:
    name: malhaebom
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  config:
    import:
      - optional:file:./config/application.yaml
      - optional:file:.env[.properties]
