spring:
  application:
    name: malhaebom
  profiles:
    default: local
  config:
    import:
      - optional:file:./config/application.yaml
      - optional:file:.env[.properties]

google:
  cloud:
    project-id: malhaebom-504606
