spring:
  lifecycle:
    timeout-per-shutdown-phase: 25s
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.ucehgosajxusjvfvmkbm
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  shutdown: graceful

malhaebom:
  cors:
    allowed-origins: https://frontend-eight-psi-26.vercel.app
