spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.gkbjfdrnxtngxnaqnkto
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

cookie:
  refresh-token:
    domain:

malhaebom:
  cors:
    allowed-origins: https://frontend-eight-psi-26.vercel.app
  assets:
    base-url: https://malhaebom-assets-prod-514090179227-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com
  stt:
    language-code: en-US
    timeout: 15s
    max-recording-duration: 15s
    google:
      project-id: malhaebom-504606
      location: global
      recognizer-id: _
      model: short
      credentials:
        location: file:/app/config/google-credentials.json
