spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.gkbjfdrnxtngxnaqnkto
    password: "${DB_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

malhaebom:
  cors:
    allowed-origins: https://frontend-eight-psi-26.vercel.app
