-- Run once while the backend is stopped. The transaction aborts if the
-- profile table already exists, which prevents an accidental rerun from
-- deleting real learning data.
BEGIN;

DO $$
BEGIN
    IF to_regclass('public.children_profiles') IS NOT NULL THEN
        RAISE EXCEPTION 'children_profiles already exists; migration was already applied';
    END IF;
END
$$;

LOCK TABLE answers,
    speech_answers,
    learning_session_questions,
    learning_sessions
    IN ACCESS EXCLUSIVE MODE;

DELETE FROM answers
WHERE session_question_id IN (
    SELECT id FROM learning_session_questions
);

DELETE FROM speech_answers
WHERE session_question_id IN (
    SELECT id FROM learning_session_questions
);

DELETE FROM learning_session_questions;
DELETE FROM learning_sessions;

CREATE TABLE children_profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    nickname    VARCHAR(30) NOT NULL,
    age         INTEGER NOT NULL,
    grade       INTEGER NOT NULL,
    level       VARCHAR(20) NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    CONSTRAINT fk_children_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_children_profiles_age
        CHECK (age >= 1),
    CONSTRAINT ck_children_profiles_grade
        CHECK (grade BETWEEN 1 AND 6),
    CONSTRAINT ck_children_profiles_level
        CHECK (level IN ('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE'))
);

CREATE UNIQUE INDEX uk_active_children_profiles_user_nickname
    ON children_profiles (user_id, nickname)
    WHERE active = TRUE;

CREATE INDEX idx_children_profiles_user_active_created
    ON children_profiles (user_id, active, created_at);

ALTER TABLE learning_sessions
    ADD CONSTRAINT fk_learning_sessions_child
    FOREIGN KEY (child_id) REFERENCES children_profiles (id);

ALTER TABLE children_profiles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE children_profiles FROM anon, authenticated;
REVOKE ALL ON SEQUENCE children_profiles_id_seq FROM anon, authenticated;

COMMIT;
